# Generated by Django 5.2.6 on 2025-10-26 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('employee_id', models.CharField(max_length=64, unique=True)),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('supervisor', 'Supervisor'), ('operator', 'Operator'), ('technician', 'Technician'), ('security', 'Security'), ('maintenance', 'Maintenance')], default='operator', max_length=32)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=120, null=True)),
                ('emergency_contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('shift_timing', models.CharField(choices=[('morning', 'Morning (6AM-2PM)'), ('afternoon', 'Afternoon (2PM-10PM)'), ('night', 'Night (10PM-6AM)'), ('day', 'Day (8AM-5PM)')], default='day', max_length=32)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('id_proof', models.FileField(blank=True, null=True, upload_to='employees/id_proofs/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employees/photos/')),
                ('embedding', models.BinaryField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.camera')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.camera')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.employee')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
