# Generated by Django 5.2.6 on 2025-10-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('attendance', 'Attendance'), ('vehicles', 'Vehicles'), ('ppe', 'PPE'), ('textile', 'Textile'), ('core', 'Core')], max_length=32)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=16)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('ip_url', models.CharField(help_text='RTSP/HTTP URL for the camera stream', max_length=255)),
                ('camera_type', models.CharField(choices=[('rtsp', 'RTSP'), ('http', 'HTTP'), ('usb', 'USB'), ('ip', 'IP Camera')], default='ip', max_length=32)),
                ('purpose', models.CharField(choices=[('attendance', 'Attendance'), ('anpr', 'ANPR (Vehicle)'), ('ppe', 'PPE Monitoring'), ('textile', 'Textile Quality'), ('general', 'General Monitoring')], default='general', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
