# Generated by Django 5.2.6 on 2025-10-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_alert_module_gate_gateaccesslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='assigned_module',
            field=models.CharField(blank=True, help_text='Assigned module for this camera', max_length=32),
        ),
        migrations.AddField(
            model_name='camera',
            name='camera_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='camera_notes',
            field=models.TextField(blank=True, help_text='Additional notes or description'),
        ),
        migrations.AddField(
            model_name='camera',
            name='gate_name',
            field=models.CharField(blank=True, help_text='Associated gate name', max_length=100),
        ),
        migrations.AddField(
            model_name='gate',
            name='gate_name',
            field=models.CharField(blank=True, help_text='Display name for the gate', max_length=100),
        ),
    ]
