# Generated by Django 5.2.6 on 2025-10-26 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('defect_type', models.CharField(max_length=64)),
                ('confidence', models.FloatField(default=0.0)),
                ('image_snapshot', models.ImageField(blank=True, null=True, upload_to='textile/defects/')),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.camera')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
