# Generated by Django 5.2.6 on 2025-10-26 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('core', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='module',
            field=models.CharField(choices=[('attendance', 'Attendance'), ('vehicles', 'Vehicles'), ('ppe', 'PPE'), ('textile', 'Textile'), ('core', 'Core'), ('gate', 'Gate Control')], max_length=32),
        ),
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gate_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('unlocked', 'Unlocked'), ('maintenance', 'Maintenance')], default='locked', max_length=20)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('last_access_time', models.DateTimeField(blank=True, null=True)),
                ('auto_lock_duration', models.IntegerField(default=10, help_text='Auto-lock after X seconds')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.camera')),
            ],
        ),
        migrations.CreateModel(
            name='GateAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('manual', 'Manual Override'), ('auto_unlock', 'Auto Unlock'), ('auto_lock', 'Auto Lock'), ('unauthorized', 'Unauthorized Access')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.employee')),
                ('gate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gate')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.vehicle')),
            ],
        ),
    ]
